# Generated by Django 4.2.30 on 2026-05-21 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("maternal_records", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OGTTOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fasting_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="空腹血糖",
                    ),
                ),
                (
                    "one_hour_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="1小时血糖",
                    ),
                ),
                (
                    "two_hour_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="2小时血糖",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("NORMAL", "正常"),
                            ("GDM", "妊娠期糖尿病"),
                            ("INCOMPLETE", "资料不完整"),
                        ],
                        default="INCOMPLETE",
                        max_length=30,
                        verbose_name="结局",
                    ),
                ),
                (
                    "threshold_json",
                    models.JSONField(blank=True, default=dict, verbose_name="阈值快照"),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(auto_now=True, verbose_name="判定时间"),
                ),
                (
                    "maternal_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ogtt_outcome",
                        to="maternal_records.maternalrecord",
                        verbose_name="孕产妇档案",
                    ),
                ),
            ],
            options={
                "verbose_name": "OGTT结局",
                "verbose_name_plural": "OGTT结局",
                "db_table": "t_ogtt_outcome",
            },
        ),
        migrations.CreateModel(
            name="LabResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_code",
                    models.CharField(
                        choices=[
                            ("FPG", "空腹血糖"),
                            ("OGTT_1H", "OGTT 1小时血糖"),
                            ("OGTT_2H", "OGTT 2小时血糖"),
                            ("TG", "甘油三酯"),
                            ("HDL_C", "高密度脂蛋白"),
                        ],
                        max_length=40,
                        verbose_name="项目编码",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(max_length=120, verbose_name="项目名称"),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=3, max_digits=8, verbose_name="检验值"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="mmol/L", max_length=30, verbose_name="单位"
                    ),
                ),
                (
                    "sampled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="采样时间"
                    ),
                ),
                (
                    "reported_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="报告时间"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        default="MANUAL", max_length=30, verbose_name="来源"
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="来源标识"
                    ),
                ),
                (
                    "is_abnormal",
                    models.BooleanField(default=False, verbose_name="异常"),
                ),
                (
                    "confirmation_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待确认"),
                            ("CONFIRMED", "已确认"),
                            ("REJECTED", "已排除"),
                        ],
                        default="PENDING",
                        max_length=30,
                        verbose_name="确认状态",
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="确认时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="确认人",
                    ),
                ),
                (
                    "maternal_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_results",
                        to="maternal_records.maternalrecord",
                        verbose_name="孕产妇档案",
                    ),
                ),
            ],
            options={
                "verbose_name": "检验结果",
                "verbose_name_plural": "检验结果",
                "db_table": "t_lab_result",
                "ordering": ["-reported_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["maternal_record", "item_code"],
                        name="t_lab_resul_materna_f529e2_idx",
                    ),
                    models.Index(
                        fields=["confirmation_status", "is_abnormal"],
                        name="t_lab_resul_confirm_b2954d_idx",
                    ),
                ],
            },
        ),
    ]

