# Generated by Django 4.2.30 on 2026-05-21 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaternalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_no",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="档案编号"
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="姓名")),
                (
                    "id_card_masked",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="证件号脱敏"
                    ),
                ),
                (
                    "id_card_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        verbose_name="证件号哈希",
                    ),
                ),
                (
                    "phone_masked",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="电话脱敏"
                    ),
                ),
                (
                    "age",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="年龄"
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="身高cm",
                    ),
                ),
                (
                    "pre_preg_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="孕前体重kg",
                    ),
                ),
                (
                    "pre_preg_bmi",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="孕前BMI",
                    ),
                ),
                (
                    "gestational_week",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="当前孕周",
                    ),
                ),
                (
                    "last_menstrual_period",
                    models.DateField(blank=True, null=True, verbose_name="末次月经"),
                ),
                (
                    "pregnancy_count",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="孕次"
                    ),
                ),
                (
                    "birth_count",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="产次"
                    ),
                ),
                (
                    "diabetes_before_pregnancy",
                    models.BooleanField(default=False, verbose_name="妊娠前糖尿病"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "在管"),
                            ("MERGED", "已合并"),
                            ("ARCHIVED", "已归档"),
                        ],
                        default="ACTIVE",
                        max_length=30,
                        verbose_name="档案状态",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("MANUAL", "手工录入"),
                            ("HIS", "HIS"),
                            ("EMR", "电子病历"),
                            ("LIS", "LIS"),
                            ("EXCEL", "Excel导入"),
                        ],
                        default="MANUAL",
                        max_length=30,
                        verbose_name="主要来源",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.department",
                        verbose_name="管理科室",
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merged_records",
                        to="maternal_records.maternalrecord",
                        verbose_name="合并到",
                    ),
                ),
                (
                    "primary_doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="责任医生",
                    ),
                ),
            ],
            options={
                "verbose_name": "孕产妇档案",
                "verbose_name_plural": "孕产妇档案",
                "db_table": "t_maternal_record",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="FieldSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=120, verbose_name="字段名")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("MANUAL", "手工录入"),
                            ("HIS", "HIS"),
                            ("EMR", "电子病历"),
                            ("LIS", "LIS"),
                            ("EXCEL", "Excel导入"),
                        ],
                        max_length=30,
                        verbose_name="来源类型",
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="来源标识"
                    ),
                ),
                (
                    "raw_value",
                    models.CharField(blank=True, max_length=500, verbose_name="原始值"),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=4, verbose_name="可信度"
                    ),
                ),
                (
                    "captured_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="采集时间"),
                ),
                (
                    "maternal_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_sources",
                        to="maternal_records.maternalrecord",
                        verbose_name="孕产妇档案",
                    ),
                ),
            ],
            options={
                "verbose_name": "字段来源",
                "verbose_name_plural": "字段来源",
                "db_table": "t_field_source",
                "ordering": ["-captured_at"],
            },
        ),
    ]

