# Generated by Django 4.2.30 on 2026-05-21 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("maternal_records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maternalrecord",
            name="current_weight_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="当前体重kg",
            ),
        ),
        migrations.AddField(
            model_name="maternalrecord",
            name="diastolic_bp",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="舒张压"
            ),
        ),
        migrations.AddField(
            model_name="maternalrecord",
            name="expected_delivery_date",
            field=models.DateField(blank=True, null=True, verbose_name="预产期"),
        ),
        migrations.AddField(
            model_name="maternalrecord",
            name="fetal_count",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="胎数"),
        ),
        migrations.AddField(
            model_name="maternalrecord",
            name="multiple_pregnancy",
            field=models.BooleanField(default=False, verbose_name="多胎妊娠"),
        ),
        migrations.AddField(
            model_name="maternalrecord",
            name="systolic_bp",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="收缩压"
            ),
        ),
        migrations.CreateModel(
            name="MergeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待审批"),
                            ("APPROVED", "已合并"),
                            ("REJECTED", "已驳回"),
                        ],
                        default="PENDING",
                        max_length=30,
                        verbose_name="状态",
                    ),
                ),
                ("reason", models.CharField(max_length=300, verbose_name="合并原因")),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审批时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审批人",
                    ),
                ),
                (
                    "source_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merge_as_source",
                        to="maternal_records.maternalrecord",
                        verbose_name="来源档案",
                    ),
                ),
                (
                    "target_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merge_as_target",
                        to="maternal_records.maternalrecord",
                        verbose_name="目标档案",
                    ),
                ),
            ],
            options={
                "verbose_name": "档案合并记录",
                "verbose_name_plural": "档案合并记录",
                "db_table": "t_maternal_merge_record",
                "ordering": ["-created_at"],
            },
        ),
    ]
