# Generated by Django 4.2.30 on 2026-05-21 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("risk", "0002_alter_riskassessment_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("maternal_records", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowupChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAIT_ACTIVATE", "待激活"),
                            ("ACTIVE", "进行中"),
                            ("CLOSED", "已关闭"),
                        ],
                        default="WAIT_ACTIVATE",
                        max_length=30,
                        verbose_name="状态",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="触发原因"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="激活时间"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="关闭时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "maternal_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followup_chains",
                        to="maternal_records.maternalrecord",
                        verbose_name="孕产妇档案",
                    ),
                ),
                (
                    "risk_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="followup_chains",
                        to="risk.riskassessment",
                        verbose_name="触发评估",
                    ),
                ),
            ],
            options={
                "verbose_name": "随访链",
                "verbose_name_plural": "随访链",
                "db_table": "t_followup_chain",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FollowupTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(max_length=120, verbose_name="任务名称"),
                ),
                (
                    "due_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="截止时间"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("DONE", "已完成"),
                            ("CANCELLED", "已取消"),
                            ("OVERDUE", "已逾期"),
                        ],
                        default="PENDING",
                        max_length=30,
                        verbose_name="状态",
                    ),
                ),
                ("result_text", models.TextField(blank=True, verbose_name="处理结果")),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="负责人",
                    ),
                ),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="followups.followupchain",
                        verbose_name="随访链",
                    ),
                ),
            ],
            options={
                "verbose_name": "随访任务",
                "verbose_name_plural": "随访任务",
                "db_table": "t_followup_task",
                "ordering": ["status", "due_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remind_at", models.DateTimeField(verbose_name="提醒时间")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待提醒"),
                            ("SENT", "已提醒"),
                            ("CANCELLED", "已取消"),
                        ],
                        default="PENDING",
                        max_length=30,
                        verbose_name="状态",
                    ),
                ),
                ("message", models.CharField(max_length=300, verbose_name="提醒内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="followups.followuptask",
                        verbose_name="随访任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统提醒",
                "verbose_name_plural": "系统提醒",
                "db_table": "t_system_reminder",
                "ordering": ["remind_at"],
            },
        ),
        migrations.CreateModel(
            name="InterventionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intervention_type",
                    models.CharField(
                        choices=[
                            ("DIET", "饮食指导"),
                            ("EXERCISE", "运动指导"),
                            ("REFERRAL", "转诊建议"),
                            ("EDUCATION", "健康宣教"),
                        ],
                        max_length=30,
                        verbose_name="干预类型",
                    ),
                ),
                ("content", models.TextField(verbose_name="干预内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions",
                        to="followups.followupchain",
                        verbose_name="随访链",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="记录人",
                    ),
                ),
            ],
            options={
                "verbose_name": "干预记录",
                "verbose_name_plural": "干预记录",
                "db_table": "t_intervention_record",
                "ordering": ["-created_at"],
            },
        ),
    ]

