# Generated by Django 4.2.30 on 2026-05-21 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="科室编码"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="科室名称")),
                (
                    "department_type",
                    models.CharField(
                        choices=[
                            ("OBSTETRICS", "产科"),
                            ("COMMUNITY", "基层门诊"),
                            ("LAB", "检验科"),
                            ("ADMIN", "管理部门"),
                        ],
                        max_length=30,
                        verbose_name="科室类型",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "科室",
                "verbose_name_plural": "科室",
                "db_table": "t_department",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("DOCTOR", "医生"),
                            ("NURSE", "护士"),
                            ("MANAGER", "医务管理"),
                            ("ADMIN", "系统管理员"),
                        ],
                        default="DOCTOR",
                        max_length=30,
                        verbose_name="角色",
                    ),
                ),
                (
                    "data_scope",
                    models.CharField(
                        choices=[
                            ("SELF", "本人"),
                            ("DEPARTMENT", "本科室"),
                            ("HOSPITAL", "全院"),
                        ],
                        default="DEPARTMENT",
                        max_length=30,
                        verbose_name="数据范围",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="联系电话"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.department",
                        verbose_name="所属科室",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户档案",
                "verbose_name_plural": "用户档案",
                "db_table": "t_user_profile",
            },
        ),
    ]

