# Generated by Django 4.2.30 on 2026-05-21 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("system_config", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetentionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="策略编码"
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="策略名称")),
                (
                    "retention_days",
                    models.PositiveIntegerField(default=3650, verbose_name="保留天数"),
                ),
                (
                    "action",
                    models.CharField(
                        default="人工复核", max_length=80, verbose_name="到期动作"
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "数据保留策略",
                "verbose_name_plural": "数据保留策略",
                "db_table": "t_retention_policy",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="RuleConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="规则编码"
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="规则名称")),
                ("description", models.TextField(blank=True, verbose_name="规则说明")),
                (
                    "config_json",
                    models.JSONField(blank=True, default=dict, verbose_name="规则配置"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "规则配置",
                "verbose_name_plural": "规则配置",
                "db_table": "t_rule_config",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ThresholdConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="阈值编码"
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="阈值名称")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="阈值"
                    ),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=30, verbose_name="单位"),
                ),
                (
                    "applies_to",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="适用场景"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "阈值配置",
                "verbose_name_plural": "阈值配置",
                "db_table": "t_threshold_config",
                "ordering": ["code"],
            },
        ),
        migrations.AlterModelOptions(
            name="modelversion",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "模型版本",
                "verbose_name_plural": "模型版本",
            },
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="activated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="启用时间"),
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="artifact_format",
            field=models.CharField(
                choices=[("PKL", "PKL"), ("JOBLIB", "Joblib"), ("ONNX", "ONNX")],
                default="PKL",
                max_length=20,
                verbose_name="文件格式",
            ),
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="artifact_path",
            field=models.CharField(max_length=500, verbose_name="文件路径"),
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="dependency_status_json",
            field=models.JSONField(blank=True, default=dict, verbose_name="依赖检查"),
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="display_name",
            field=models.CharField(max_length=200, verbose_name="显示名称"),
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="feature_schema_json",
            field=models.JSONField(blank=True, default=dict, verbose_name="特征结构"),
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="input_schema_json",
            field=models.JSONField(blank=True, default=dict, verbose_name="输入结构"),
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="manifest_json",
            field=models.JSONField(blank=True, default=dict, verbose_name="发布清单"),
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="model_family",
            field=models.CharField(
                choices=[
                    ("XGBOOST", "XGBoost"),
                    ("SKLEARN", "Scikit-learn"),
                    ("UNKNOWN", "未知"),
                ],
                default="XGBOOST",
                max_length=30,
                verbose_name="模型家族",
            ),
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="model_type",
            field=models.CharField(
                choices=[("FULL", "完整模型"), ("DEGRADED", "降级模型")],
                default="FULL",
                max_length=20,
                verbose_name="模型类型",
            ),
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="output_schema_json",
            field=models.JSONField(blank=True, default=dict, verbose_name="输出结构"),
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="predecessor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="successors",
                to="system_config.modelversion",
                verbose_name="前序版本",
            ),
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="retired_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="停用时间"),
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="sha256",
            field=models.CharField(max_length=64, verbose_name="SHA256"),
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "草稿"),
                    ("VALIDATING", "验证中"),
                    ("STAGED", "待启用"),
                    ("PRODUCTION", "生产中"),
                    ("RETIRED", "已停用"),
                    ("FAILED", "验证失败"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="status_message",
            field=models.TextField(blank=True, verbose_name="状态说明"),
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="validation_report_json",
            field=models.JSONField(blank=True, default=dict, verbose_name="验证报告"),
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="version_code",
            field=models.CharField(
                max_length=120, unique=True, verbose_name="版本编码"
            ),
        ),
    ]

