# Generated by Django 4.2.30 on 2026-05-21 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("system_config", "0002_retentionpolicy_ruleconfig_thresholdconfig_and_more"),
        ("maternal_records", "0001_initial"),
        ("risk", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="riskassessment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "风险评估",
                "verbose_name_plural": "风险评估",
            },
        ),
        migrations.AddField(
            model_name="riskassessment",
            name="assessment_no",
            field=models.CharField(blank=True, max_length=80, verbose_name="评估编号"),
        ),
        migrations.AddField(
            model_name="riskassessment",
            name="data_completeness_json",
            field=models.JSONField(blank=True, default=dict, verbose_name="完整性检查"),
        ),
        migrations.AddField(
            model_name="riskassessment",
            name="maternal_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="risk_assessments",
                to="maternal_records.maternalrecord",
                verbose_name="孕产妇档案",
            ),
        ),
        migrations.AlterField(
            model_name="riskassessment",
            name="assessment_status",
            field=models.CharField(
                default="DONE", max_length=30, verbose_name="评估状态"
            ),
        ),
        migrations.AlterField(
            model_name="riskassessment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="riskassessment",
            name="degradation_reason",
            field=models.TextField(blank=True, verbose_name="降级原因"),
        ),
        migrations.AlterField(
            model_name="riskassessment",
            name="engine_type",
            field=models.CharField(
                choices=[
                    ("FULL_MODEL", "完整模型"),
                    ("DEGRADED_MODEL", "降级模型"),
                    ("RULE_ONLY", "规则评估"),
                    ("EXCLUDED", "已排除"),
                ],
                max_length=30,
                verbose_name="评估引擎",
            ),
        ),
        migrations.AlterField(
            model_name="riskassessment",
            name="model_trace_json",
            field=models.JSONField(blank=True, default=dict, verbose_name="模型追踪"),
        ),
        migrations.AlterField(
            model_name="riskassessment",
            name="model_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="system_config.modelversion",
                verbose_name="模型版本",
            ),
        ),
        migrations.AlterField(
            model_name="riskassessment",
            name="result_json",
            field=models.JSONField(blank=True, default=dict, verbose_name="评估结果"),
        ),
        migrations.AlterField(
            model_name="riskassessment",
            name="risk_level",
            field=models.CharField(
                blank=True,
                choices=[("LOW", "低危"), ("MEDIUM", "中危"), ("HIGH", "高危")],
                max_length=20,
                verbose_name="风险等级",
            ),
        ),
        migrations.AlterField(
            model_name="riskassessment",
            name="risk_probability",
            field=models.FloatField(blank=True, null=True, verbose_name="风险概率"),
        ),
        migrations.CreateModel(
            name="PreExclusionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("NOT_EXCLUDED", "未排除"), ("EXCLUDED", "已排除")],
                        max_length=30,
                        verbose_name="排除结论",
                    ),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=200, verbose_name="原因"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "maternal_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pre_exclusion_records",
                        to="maternal_records.maternalrecord",
                        verbose_name="孕产妇档案",
                    ),
                ),
            ],
            options={
                "verbose_name": "预排除记录",
                "verbose_name_plural": "预排除记录",
                "db_table": "t_pre_exclusion_record",
                "ordering": ["-created_at"],
            },
        ),
    ]

