# Generated by Django 4.2.30 on 2026-05-21 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("VIEW", "查看"),
                            ("CREATE", "创建"),
                            ("UPDATE", "修改"),
                            ("EXPORT", "导出"),
                            ("ACTIVATE_MODEL", "启用模型"),
                            ("IMPORT", "导入"),
                        ],
                        max_length=40,
                        verbose_name="操作",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(max_length=80, verbose_name="对象类型"),
                ),
                (
                    "target_id",
                    models.CharField(blank=True, max_length=80, verbose_name="对象ID"),
                ),
                ("summary", models.CharField(max_length=300, verbose_name="摘要")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "metadata_json",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "审计日志",
                "verbose_name_plural": "审计日志",
                "db_table": "t_audit_log",
                "ordering": ["-created_at"],
            },
        ),
    ]

