# Generated by Django 4.2.30 on 2026-05-21 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IntegrationSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="接入源编码"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="接入源名称")),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("HIS", "HIS/EMR"),
                            ("LIS", "LIS"),
                            ("EXCEL", "Excel导入"),
                            ("MANUAL", "手工录入"),
                        ],
                        max_length=30,
                        verbose_name="接入类型",
                    ),
                ),
                (
                    "adapter_path",
                    models.CharField(
                        default="integrations.adapters.MockAdapter",
                        max_length=200,
                        verbose_name="适配器路径",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "config_json",
                    models.JSONField(blank=True, default=dict, verbose_name="配置"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "接入源",
                "verbose_name_plural": "接入源",
                "db_table": "t_integration_source",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        default="PULL", max_length=60, verbose_name="任务类型"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待执行"),
                            ("RUNNING", "执行中"),
                            ("SUCCESS", "成功"),
                            ("FAILED", "失败"),
                        ],
                        default="PENDING",
                        max_length=30,
                        verbose_name="状态",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "pulled_count",
                    models.PositiveIntegerField(default=0, verbose_name="读取数量"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="integrations.integrationsource",
                        verbose_name="接入源",
                    ),
                ),
            ],
            options={
                "verbose_name": "接入任务",
                "verbose_name_plural": "接入任务",
                "db_table": "t_integration_task",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=260, verbose_name="文件名")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRECHECK", "预检查"),
                            ("IMPORTED", "已导入"),
                            ("FAILED", "失败"),
                        ],
                        default="PRECHECK",
                        max_length=30,
                        verbose_name="状态",
                    ),
                ),
                (
                    "total_rows",
                    models.PositiveIntegerField(default=0, verbose_name="总行数"),
                ),
                (
                    "success_rows",
                    models.PositiveIntegerField(default=0, verbose_name="成功行数"),
                ),
                (
                    "failed_rows",
                    models.PositiveIntegerField(default=0, verbose_name="失败行数"),
                ),
                (
                    "error_json",
                    models.JSONField(blank=True, default=list, verbose_name="错误明细"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="integrations.integrationsource",
                        verbose_name="接入源",
                    ),
                ),
            ],
            options={
                "verbose_name": "导入批次",
                "verbose_name_plural": "导入批次",
                "db_table": "t_import_batch",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FieldMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_field",
                    models.CharField(max_length=120, verbose_name="来源字段"),
                ),
                (
                    "target_model",
                    models.CharField(max_length=80, verbose_name="目标模型"),
                ),
                (
                    "target_field",
                    models.CharField(max_length=120, verbose_name="目标字段"),
                ),
                ("required", models.BooleanField(default=False, verbose_name="必填")),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="integrations.integrationsource",
                        verbose_name="接入源",
                    ),
                ),
            ],
            options={
                "verbose_name": "字段映射",
                "verbose_name_plural": "字段映射",
                "db_table": "t_field_mapping",
                "unique_together": {
                    ("source", "source_field", "target_model", "target_field")
                },
            },
        ),
    ]

